version: "3"

volumes:
    db_volume: {}

services:
    db:
        container_name: transign_db
        restart: always
        image: postgres
        volumes:
            - db_volume:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=database
            - POSTGRES_USER=transign
            - POSTGRES_PASSWORD=transignpassword
            - POSTGRES_INITDB_ARGS=--encoding=UTF-8
    transign_grpc:
        container_name: transign_grpc
        restart: always
        depends_on:
            - "db"
        build:
            context: .
            dockerfile: ./cmd/server/Dockerfile
        environment:
            - DB_HOST=transign_db
            - DB_USERNAME=transign
            - DB_PASSWORD=transignpassword
        ports:
            - "8080:8080"
    transign_httpproxy:
        container_name: transign_httpproxy
        restart: always
        depends_on:
            - "transign_grpc"
        build:
            context: .
            dockerfile: ./cmd/httpproxy/Dockerfile
        environment:
            - "PROXY_DESTINATION=transign_grpc:8080"
        ports:
            - "8000:8000"
